Implement ReferenceParser from JSONParser code abstraction.
dbbs-lab/bsb-yaml pull request #4
Opened 2024-05-07 15:58 UTC by drodarie

Should be merged after https://github.com/dbbs-lab/bsb-core/pull/839
Closes #3

2024-05-14 09:31 UTC, Helveg commented
> Should be merged after https://github.com/dbbs-lab/bsb-core/pull/839

Should be merged after https://github.com/dbbs-lab/bsb-core/pull/839 is released as `bsb-core==4.1.0` * 😋

2024-05-21 14:45 UTC, Helveg requested changes

2024-05-21 14:45 UTC, Helveg commented on bsb_yaml/parser.py
> -
This needn't be removed, does it?

2024-05-21 14:52 UTC, drodarie commented on bsb_yaml/parser.py
> -
Sorry my bad

2024-05-21 14:54 UTC, Helveg approved these changes

2024-05-21 15:00 UTC, merged